# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "en-gb"
title: Alfie Pates
description: A telecomms human, musician, and photographer living in Edinburgh.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.alfiepates.me" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/alfie-square-1200px.jpg
permalink: pretty

author:
  name: Alfie
  picture: /assets/images/alfie-square-1200px.jpg

footer_links:
  - title: GitHub
    url: https://github.com/alfiepates
    icon: fab fa-github-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/alfiepates/
    icon: fab fa-linkedin
  - title: Flickr
    url: https://www.flickr.com/photos/alfiepates/
    icon: fab fa-flickr

# Build settings
markdown: kramdown
theme: jekyll-theme-so-simple
plugins:
  - jekyll-feed

# Fonts stuff - see /assets/css/main.scss
google_fonts:
- name: "Lora"
  weights: "400,400i,700,700i"
- name: "Source Sans Pro"
  weights: "400,400i,700,700i"

# Prose config: see https://github.com/prose/prose/wiki/Prose-Configuration

prose:
  siteurl: https://www.alfiepates.me/
  media: /assets/images/
  ignore:
    - /assets/css
    - Gemfile
    - Gemfile.lock
    - .gitignore
  metadata:
      _posts:
        - name: "layout"
          field:
            element: "hidden"
            value: "post"
        - name: "title"
          field:
            element: "text"
            label: "Title"
            value: ""
      reviews/_posts:
        - name: "layout"
          field:
            element: "hidden"
            value: "post"
        - name: "category"
          field:
            element: "hidden"
            value: "reviews"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
